mysql:
  host: 'localhost:3306'
  username: 'root'
  password: '1'
  database: 'cwcore'
  ssl: true

ignored-servers: ['reg-limbo']

colors:
  'reputation > 4': '#6495ED'
  'reputation > 9': '#7FFF00'
  'reputation > 14': '#B8860B'

premium-permission: 'group.premium'

premium:
  custom-color: true

discord:
  token: ''